### ISSUE TITLE
프로그래머스 인공지능 과제 예제 같이 해보실분

### ISSUE THREAD

**Issue by DrunkJin** [DrunkJin/CosMos#4]
https://programmers.co.kr/skill_check_assignments/1

이거 같이 해보실분?

**Comment by brain4652** [comment]
이거 얼마나 걸리나요? 일단 발표 ppt먼저 만들고.. ㅠ 보겠습니다.

**Comment by likelion-Jiyeong** [comment]
저는 일단은 코테 문제풀이에 조금 더 집중해보겠습니당ㅜㅜㅜ

**Comment by DrunkJin** [comment]
@brain4652 시간은 일주일 주는데 뇌가 굳어서 지금 어떻게 접근해야될지 감이 안오고 있어서 같이 해보고 싶어가지구...
@likelion-Jiyeong  네네
