### ISSUE TITLE
이 문제 어떤 개념인지 설명해주실 분 구합니다

### ISSUE THREAD

**Issue by DrunkJin** [DrunkJin/CosMos#6]
https://leetcode.com/problems/remove-duplicates-from-sorted-array/

list변경이 안먹어요

**Comment by brain4652** [comment]
자체적인 채점 로직이 있는 것 같은데
좋은 문제 같진 않네요..

**Comment by DrunkJin** [comment]
영어가 후달리는게 이렇게도 슬프다니
