### ISSUE TITLE
방학이 끝났습니다 여러분~ 코테하러오세요!

### ISSUE THREAD

**Issue by DrunkJin** [DrunkJin/CosMos#7]
# [🔥평생무료🔥코😜테😚하러가기!!!클🤪릭😍](https://github.com/DrunkJin/CosMos/)

**Comment by likelion-Jiyeong** [comment]
너무 오래 쉬었네요ㅎㅎㅎ 금방 돌아올게요~!!

**Comment by DrunkJin** [comment]
> 너무 오래 쉬었네요ㅎㅎㅎ 금방 돌아올게요~!!

쉬운문제 많으니 머리아플때 한번 슉슉 봐주세용
